Malaria_Portal/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(
        template_name='home.html'
    ), name='home'),
    path('about/', TemplateView.as_view(
        template_name='about.html'
    ), name='about'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('portal/', include('portal.urls', namespace='portal')),
]

Malaria_Portal/portal/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from portal import views

app_name='portals'

urlpatterns = [
    path('', login_required(views.TemplateView.as_view(template_name = 'portal/home.html')), name='home'),
    path('patient/add/', views.PatientAdd.as_view(), name='patient_add'),
    path('patients/', views.PatientList.as_view(), name='patient_list'),
    path('patients/<int:pk>', views.PatientDetail.as_view(), name='patient_detail'),
    path('patient/diagnosis/', views.Diagnosis.as_view(), name='diagnosis'),
    path('patient/adherence/report/<int:pk>', views.AdherenceTest.as_view(), name='adherence'),
    path('training_data/', views.TrainingData.as_view(), name="training_data"),
]

Malaria_Portal/malaria/models.py
from django.db import models
from django.shortcuts import reverse

class Patient(models.Model):
    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female')
    )

    full_name       = models.CharField(max_length=30)
    gender          = models.CharField(choices=GENDER_CHOICES, max_length=1)
    date_of_birth   = models.DateField()
    registered_on   = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)
    
    def get_absolute_url(self):
        return reverse('portal:patient_detail', kwargs={'pk': self.pk})


class Report(models.Model):
    patient             = models.ForeignKey(Patient, on_delete=models.CASCADE)
    has_malaria         = models.NullBooleanField()
    adhered_to_treatment = models.NullBooleanField()
    generated_on        = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.patient.full_name
    
    class Meta:
        ordering = ["-generated_on"]


class DiagnosisQuestion(models.Model):
    question_text       = models.CharField(max_length=100)

    def __str__(self):
        return self.question_text

    class Meta:
        ordering = ["id"]



class AdherenceQuestion(models.Model):
    question_text   = models.CharField(max_length=100)

    def __str__(self):
        return self.question_text
    
    class Meta:
        ordering = ["id"]

Malaria_Portal/portal/models.py
from django.db import models

# Create your models here.

Malaria_Portal/malaria/forms.py
from django import forms

from .models import Patient

class PatientForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    class Meta:
        model = Patient
        fields = ('full_name', 'gender', 'date_of_birth')

Malaria_Portal/malaria/views.py
from django.shortcuts import render

# Create your views here.

Malaria_Portal/portal/views.py
import os
import pickle
import numpy as np
import pandas as pd

from django.shortcuts import render, redirect, reverse
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.views.generic.base import TemplateResponseMixin, ContextMixin
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from malaria.models import Patient, DiagnosisQuestion, AdherenceQuestion, Report
from malaria.forms import PatientForm


CLASSIFIER_BASE = os.path.join(settings.BASE_DIR, 'malaria', 'classifiers')


class PatientAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = PatientForm
    template_name = 'malaria/patient_form.html'
    success_message = 'Patient Created Successfully'


class PatientList(LoginRequiredMixin, ListView):
    model = Patient


class PatientDetail(LoginRequiredMixin, DetailView):
    model = Patient

class TrainingData(LoginRequiredMixin, TemplateView):
    template_name = "portal/training_data.html"
    
class Diagnosis(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        questions = DiagnosisQuestion.objects.all()
        patients = Patient.objects.all()
        context = {
            'questions': questions,
            'patients': patients,
        }
        return render(request, 'portal/diagnosis.html', context)

    def post(self, request, *args, **kwargs):
        patient_id = int(request.POST.get('patient'))
        patient = Patient.objects.get(id=patient_id)
        request_count = len(request.POST)-2
        choices = [int(request.POST.get('choice'+str(q+1))) for q in range(request_count)]
        print(choices)

        pickle_in = open(os.path.join(CLASSIFIER_BASE, 'malaria_prediction.pkl'), 'rb')
        clf_malaria = pickle.load(pickle_in)
        # answers = pd.DataFrame([[0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0]])
        answers = pd.DataFrame([choices])
        result = clf_malaria.predict(answers)
        print('Severe Malaria', result)
        possible_results = ['YES', 'NO']
        if result in possible_results:
            Report.objects.create(
                patient=patient,
                has_malaria=True if result == ['YES'] else False
            )
            messages.success(request, "Diagnosis Completed")
            return redirect(patient)
        messages.error(request, "Something went wrong!")
        return render(request, 'portal/diagnosis.html', {})


class AdherenceTest(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        questions = AdherenceQuestion.objects.all()
        report_id = kwargs.get('pk')
        report = Report.objects.get(id=report_id)
        context = {
            'questions': questions,
            'patient': report.patient,
        }
        return render(request, 'portal/adherence.html', context)
    
    def post(self, request, *args, **kwargs):
        report_id = kwargs.get('pk')
        report = Report.objects.get(id=report_id)
        request_count = len(request.POST)-1
        choices = [int(request.POST.get('choice'+str(q+1))) for q in range(request_count)]
        print(choices)

        pickle_in = open(os.path.join(CLASSIFIER_BASE, 'adherence_prediction.pkl'), 'rb')
        clf_adh = pickle.load(pickle_in)
        # answers = pd.DataFrame([[0, 0, 0, 0, 1, 0, 1, 1, 1, 1]])
        answers = pd.DataFrame([choices])
        result = clf_adh.predict(answers)
        print('Adhered', result)
        possible_results = ['YES', 'NO']
        if result in possible_results:
            report.adhered_to_treatment = True if result == ['YES'] else False
            report.save()
            messages.success(request, "Adherence Test Completed")
            return redirect(report.patient)
        messages.error(request, "Something went wrong!")
        return render(request, 'portal/adherence.html', {})




Malaria_Portal/malaria/templates/malaria/patient_detail.html
{% extends "base.html" %}

{% block content %}



<div class="container mt-3">
    <div class="mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'portal:home' %}">Portal</a></li>
                <li class="breadcrumb-item"><a href="{% url 'portal:patient_list' %}">Patients</a></li>
                <li class="breadcrumb-item active" aria-current="page">Patient</li>
            </ol>
        </nav>
    </div>

    <div class="card bg-light">
        <div class="card-body">
            <h2>Patient: {{ patient.full_name }}</h2>
            <p><strong>Card No: </strong>{{ patient.id }}</p>
            <p><strong>Gender: </strong>{{ patient.gender }}</p>
            <p><strong>Date of Birth:</strong> {{ patient.date_of_birth }}</p>
            <p><strong>Registered On: </strong>{{ patient.registered_on }}</p>
        </div>
    </div>

    <h2 class="mt-2">ECG History</h2>

        <div class="row">
            <div class="col-12">
                
                {% if patient.report_set.exists %}
                    <div class="table-responsive">
                        <table class="table table-hover ">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">Diagnosis Date</th>
                                <th scope="col">Has Malaria</th>
                                <th scope="col">Prescribed Drugs</th>
                                <th scope="col">Adhered To Treatment</th>
                                <th scope="col">Take Adherence Test</th>
                            </tr>
                            </thead>
                            <tbody>
                            
                            {% for report in patient.report_set.all %}
                                <tr>
                                    <td>{{ report.generated_on }}</td>
                                    <td>{{ report.has_malaria }}</td>
                                    <td>Artemether &amp; Lumefantrine</td>
                                    <td>{{ report.adhered_to_treatment }}</td> 
                                    {% if report.has_malaria and report.adhered_to_treatment is None %}
                                        <td><a href="{% url 'portal:adherence' report.id %}" class="btn btn-danger">Perform Test</a></td>
                                    {% endif %}   
                                </tr>
                            {% endfor %}
                                
                            
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="alert alert-info messages">
                        <span class="alert-info">Patient has never been diagnosed!</span>
                    </div>
                {% endif %}
                    
                
            </div>
        </div>  
</div>
{% endblock content %}
    

Malaria_Portal/malaria/templates/malaria/patient_form.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="col">
            <div class="row justify-content-center mt-4">
                <div class="col-md-6 col-sm-8">
                  <div class="card">
                    <div class="card-body">
                      <h3 class="card-title">Add Patient</h3>
                      <form method="post" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                        {% include 'base/form.html' %}
                        <button type="submit" class="btn btn-info">Create</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
        </div>
    </div>
{% endblock content %}
    

Malaria_Portal/malaria/templates/malaria/patient_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
        <div class="mt-2">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'portal:home' %}">Portal</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Patients</li>
                </ol>
            </nav>
        </div>
    <h2>Patients</h2>

        <div class="row">
            <div class="col-12">
                <table class="table">
                <thead>
                <tr>
                    <th scope="col">Card No</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">View</th>
                </tr>
                </thead>
                <tbody>
                
                {% for patient in patient_list %}
                    <tr>
                        <td>{{ patient.id }}</td>
                        <td>{{ patient.full_name }}</td>
                        <td><a href="{% url 'portal:patient_detail' patient.pk %}" class="btn btn-info">View</a></td>
                    </tr>
                {% endfor %}
                    
                
                </tbody>
            </table>
            </div>
        </div>  
</div>  

{% endblock content %}
    

Malaria_Portal/portal/templates/portal/adherence.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'portal:home' %}">Portal</a></li>
                <li class="breadcrumb-item"><a href="{% url 'portal:patient_list' %}">Patients</a></li>
                <li class="breadcrumb-item"><a href="{{ patient.get_absolute_url }}">{{ patient.full_name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Aherence Test</li>
            </ol>
        </nav>
    </div>
    <h2>Adherence Test</h2>

    {% include "portal/snippets/questions_form.html" with test_questions=questions is_diagnosis=False %}

</div>
{% endblock content %}

Malaria_Portal/portal/templates/portal/diagnosis.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'portal:home' %}">Portal</a></li>
                <li class="breadcrumb-item active" aria-current="page">Diagnosis</li>
            </ol>
        </nav>
    </div>

    <h2>Diagnosis</h2>

    {% include "portal/snippets/questions_form.html" with test_questions=questions is_diagnosis=True %}
        
</div>
{% endblock content %}
    

Malaria_Portal/portal/templates/portal/home.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron text-center">
    <h1 class="display-6">Portal</h1>
    <p class="lead">Manage your patients for ECG diagnosis</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <a href="{% url 'portal:patient_add' %}">
                <div class="card text-white bg-info mb-3 p-4 text-center">
                    <div class="card-body">
                            <h2 class="card-text text-light">Add Patient</h2>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-4">
            <a href="{% url 'portal:patient_list' %}">
                <div class="card text-white bg-info mb-3 p-4 text-center">
                    <div class="card-body">
                            <h2 class="card-text text-light">Patient's History</h2>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-4">
            <a href="{% url 'portal:diagnosis' %}">
                <div class="card text-white bg-info mb-3 p-4 text-center">
                    <div class="card-body">
                            <h2 class="card-text text-light">Diagnose Patient</h2>
                    </div>
                </div>
            </a>
        </div>

    </div>

</div>
{% endblock content %}
    

Malaria_Portal/portal/templates/portal/snippets/questions_form.html

<form action="" method="post">
    {% csrf_token %}
    
    {% if is_diagnosis %}
        <label for="patient">Select patient to Diagnose</label>
        <select name="patient" class="form-control" id="patient" required>
            <option value selected>Select Patient</option>
            {% for p in patients %}
                <option value="{{ p.id }}">{{ p.full_name }}</option>
            {% endfor %}
        </select>
    {% endif %}      

    <div class="row">
    {% for q in test_questions %}
        <div class="col-sm-6 col-md-4">
            <div class="card bg-light" style="margin: 20px 0;">
                <div class="card-body">
                    <h4 class="card-title">{{ q.question_text }}</h4>
                    <label for="yes{{forloop.counter}}">
                        <input type="radio" name="choice{{forloop.counter}}" id="yes{{forloop.counter}}" value="1" required />
                        Yes
                    </label><br />
                    <label for="no{{forloop.counter}}">
                        <input type="radio" name="choice{{forloop.counter}}" id="no{{forloop.counter}}" value="0" required />
                        No
                    </label><br />
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="d-flex justify-content-end" style="margin: 40px 0;">
        <input type="submit" class="btn btn-info btn-lg" value="Submit" />
    </div>
</form>
        

Malaria_Portal/portal/templates/portal/training_data.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="jumbotron text-center">
    <h1 class="display-6">Training Data</h1>
    <p class="lead">Download the Training Data for diagnosis and adherence tests.</p>
</div>

<div class="container">
    <h3>Downloads</h3>
    <div class="row">
        <div class="col-12">
            <a href="{% static 'resources/malaria_prediction_data.csv' %}" class="btn btn-outline-warning btn-lg">Diagnosis Data</a>
            <a href="{% static 'resources/adherence_questionnaire.csv' %}" class="btn btn-outline-success btn-lg">Adherence Data</a>

        </div>
    </div>

</div>
{% endblock content %}
    

Malaria_Portal/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="col">
            <div class="row justify-content-center mt-4">
                <div class="col-lg-4 col-md-6 col-sm-8">
                  <div class="card">
                    <div class="card-body">
                      <h3 class="card-title">Log in</h3>
                      <form method="post" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                        {% include 'base/form.html' %}
                        <button type="submit" class="btn btn-info btn-block">Log in</button>
                      </form>
                    </div>
                    <div class="card-footer text-muted text-center">
                    </div>
                  </div>
                </div>
              </div>
        </div>
    </div>
{% endblock content %}
    

Malaria_Portal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Hopewell Clinic</title>
    {% include 'base/css.html' %}
    {% block base_head %}{% endblock %}
</head>
<body>
  {% include 'base/navbar.html' %}
  <div class='container'>
    
    {% if messages %}
      {% for message in messages %}
        <div class="alert {{message.tags}} messages alert-dismissible fade show" role="alert">
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}<br/>
          </span>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}

    
  </div>
    
  {% block content %}{% endblock %}

    {% include 'base/js.html' %}

    {% block javascript %}
    
    {% endblock javascript %}

  </body>
</html>

Malaria_Portal/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

Malaria_Portal/templates/base/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

Malaria_Portal/templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

Malaria_Portal/templates/base/navbar.html
{% url 'home' as home %}
{% url 'about' as about %}
{% url 'login' as login %}
{% url 'portal:home' as portal_home %}

<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/"><i>&#x1f3e5;</i><span class="pl-1">Hopewell Clinic</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link {% if request.path == home %}active{% endif %}" href="/">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link {% if request.path == portal_home %}active{% endif %}" href="{% url 'portal:home' %}">Portal</a>
        
        {% if request.user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-item nav-link {% if request.path == login %}active{% endif %}" href="{% url 'login' %}">Login</a>
        {% endif %}
          
      </div>
    </div>
  </nav>

Malaria_Portal/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron jmb-bg">
    <div class="jmb-light">
      <h1 class="display-6">Malaria Diagnosis and Adherence Application</h1>
	<p class="lead">
       	 <a class="btn btn-info btn-lg" href="#" role="button">Learn More</a>
      </p>
    </div>
  </div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Malaria</h2>
      <p>Malaria is one of the major public health problems in Nigeria. Early prediction of a Malaria outbreak is the key for control of malaria morbidity, mortality as well as reducing the risk of transmission of malaria in the community and can help policymakers, health providers, medical officers, ministry of health and other health organizations to better target medical resources to areas of greatest need.  </p>
      <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Adherence</h2>
      <p>Adherence rates decrease as patients stay longer with the condition. Medication non-adherence is thought to be the most common cause of Malaria exacerbation and subsequent hospital readmission in patients with malaria. Because of the importance of medication adherence in managing malaria, a full understanding of the factors associated with medication adherence in patients with malaria is needed so that effective interventions to improve medication adherence can be developed. In Western countries, studies related to application of SVM in cardiovascular patients have been continuously conducted. </p>
      <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Malaria</h2>
      <p>Malaria is a condition characterized by unpleasant symptoms, high mortality, recurrent hospitalization and significant cost burden. Estimates of medication adherence rates in patients with Malaria range from 7% to 90%, depending on the definition and how adherence is measured. </p>
      <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}
    